### PR TITLE
Added Bean Eater Loader

### PR DESCRIPTION
**Pull request by sm9416220**
Please merge it

### CODE REVIEW

**Comment by UsmanAhmadSaeed** [comment]
@sm9416220 Please read our guidelines and update accordingly. Loader could be centered, and more optimized too.
I'll add the hacktoberfest-accepted label when you comment back today.

**Comment by sm9416220** [comment]
@UsmanAhmadSaeed ok I'll try it

**Comment by sm9416220** [comment]
@UsmanAhmadSaeed I have made the desired changes, Please look into it.

**Comment by UsmanAhmadSaeed** [comment]
@sm9416220 I'll review and update.
Thanks!

**Pull request closed without merging**
