### PR TITLE
Added an RGB hover button animation in the hover animation

### PR DESCRIPTION
**Pull request by udit9876gupta**

### CODE REVIEW

**Comment by UsmanAhmadSaeed** [comment]
@udit9876gupta please see contribution guidelines and update accordingly.

**Comment by udit9876gupta** [comment]
> @udit9876gupta please see contribution guidelines and update accordingly.

what should i add or update according to contribution guideline, please guide me.

**Comment by UsmanAhmadSaeed** [comment]
@udit9876gupta have you read through the guidelines? 
For instance, follow coding best practices, that includes commenting your code properly etc.

**Comment by udit9876gupta** [comment]
i have provided comments in the css file. Please check it.

**Comment by UsmanAhmadSaeed** [comment]
@DevKosov I've checked. seems fine. Take a look and proceed

**Pull request merged**
