### PR TITLE
Added more card hover animations

### PR DESCRIPTION
**Pull request by surajkumar345678**
Issue no. #50 
- Changes: Added 6 more card hover animations with new hover effects.
- Changes: Added animations on the title of the page and hover effects.
- Fixed Issue: Fixed some card positioning issues.
Please review my code and add it to your repository with the label hactoberfest.

### CODE REVIEW

**Comment by UsmanAhmadSaeed** [comment]
@surajkumar345678 could you please add descriptive comments so as to make it easy for anyone to reuse the code for any specific card they might want.
You have already done a great job, so maybe just add a simple "how to" at the top of file for ease of beginners.

**Comment by surajkumar345678** [comment]
Sir, please review my code, I have added some descriptive comments.

**Comment by UsmanAhmadSaeed** [comment]
@surajkumar345678 could you please do the same for stylesheet?

**Comment by surajkumar345678** [comment]
Comments added for the stylesheet.
Please review my code.

**Comment by surajkumar345678** [comment]
Sir, can you please label this PR as hactoberfest?

**Comment by UsmanAhmadSaeed** [comment]
@surajkumar345678 any PRs that are merged into a hacktoberfest participating repo are automatically considered in hacktoberfest and don't need to be labelled separately.

**Pull request merged**
