### PR TITLE
Login Form Animation

### PR DESCRIPTION
**Pull request by Pggeeks**
**#hacktoberfest     #hacktoberfest2022**

https://user-images.githubusercontent.com/82941619/194822674-c223fd9b-84f2-49e4-9775-44c54074b3a6.mp4

### CODE REVIEW

**Comment by UsmanAhmadSaeed** [comment]
@Pggeeks I'll review and update!
If your code doesn't contain comments, make sure to do so.

**Comment by UsmanAhmadSaeed** [comment]
@Pggeeks comments are not there. Also, in my opinion a slight transition on hover of submit button might be better.

**Comment by Pggeeks** [comment]
> @Pggeeks comments are not there. Also, in my opinion a slight transition on hover of submit button might be better.

Done ✔️ @UsmanAhmadSaeed 
- Added Comments in The Code
- Added On hover on the Login Button
- Centered in Login Button

**Comment by UsmanAhmadSaeed** [comment]
@Pggeeks I've checked the PR again and comments are not really helpful. Please read this for a general overview of coding best practices.
https://www.thinkful.com/blog/coding-best-practices/

**Comment by UsmanAhmadSaeed** [comment]
@Pggeeks I've checked the PR again and comments are not really helpful. Please read this for a general overview of coding best practices.
https://www.thinkful.com/blog/coding-best-practices/

**Comment by Pggeeks** [comment]
@UsmanAhmadSaeed Added new & lots of comments.
thank you for noting my mistake.

**Pull request merged**
