### PR TITLE
Add: Input Field Animations

### PR DESCRIPTION
**Pull request by renzien**
Hi! @UsmanAhmadSaeed I've been added Input Field Animations. I hope you can review it

### CODE REVIEW

**Comment by UsmanAhmadSaeed** [comment]
@renzien I'll check and update!

**Comment by renzien** [comment]
Okay! I'll be waiting @UsmanAhmadSaeed

**Comment by renzien** [comment]
@UsmanAhmadSaeed Alright, let me take a look!

**Comment by renzien** [comment]
Hi! @UsmanAhmadSaeed Sorry for bothering you again. I've already updated the comment on code, and the glitch in email box, is the bouncing animation. Sorry for the mistake. I hope i can be accepted

**Comment by UsmanAhmadSaeed** [comment]
@renzien thanks for the update. I reviewed again.
1. Comments are meant to be descriptive and concise so that they clearly explain what the code does and how it does that, i.e. the logic. I believe you can do better.
2. The glitch is still there. I'm attaching a video for better communication on what I mean

https://user-images.githubusercontent.com/20966983/195383143-19e602d0-2011-407e-94a3-8ddbf5ae1a15.mp4

**Comment by renzien** [comment]
Hi! @UsmanAhmadSaeed I've been updating the desc comment. And also, i have been fixing the email animations. So, i will put the video, for the result. I hope it can be accepted.

https://user-images.githubusercontent.com/77705313/195392814-85ce6c2f-d1c7-4fa5-aed3-b3a46a664106.mp4

**Comment by UsmanAhmadSaeed** [comment]
@renzien great work. one last thing. I believe the animations are glitching in Firefox because you haven't added compatibility for these browsers. Please create three instances of properties such as transform and use relevant prefixes 
image

**Comment by renzien** [comment]
@UsmanAhmadSaeed Ahh, yess i forgot to input compatibility. Okay, thank you for reminding me. I will fix it soon!

**Pull request closed without merging**
