### PR TITLE
New animation

### PR DESCRIPTION
**Pull request by Yash-RajSingh**

### CODE REVIEW

**Comment by UsmanAhmadSaeed** [comment]
@Yash-RajSingh Please review contribution guidelines and adhere to them, such as properly commenting your code.
Opinion: I think the underline could be made more stylish to make it appear like a road or path with walls, or at least just thin the underline.

**Comment by Yash-RajSingh** [comment]
> @Yash-RajSingh Please review contribution guidelines and adhere to them, such as properly commenting your code. Opinion: I think the underline could be made more stylish to make it appear like a road or path with walls, or at least just thin the underline.

Is it okay now?

**Comment by UsmanAhmadSaeed** [comment]
@Yash-RajSingh  There's a gap when balls are inside the circle. Not sure that was intentional. Also, apply coding best practices, such as proper comments etc.

**Comment by Yash-RajSingh** [comment]
> @Yash-RajSingh There's a gap when balls are inside the circle. Not sure that was intentional. Also, apply coding best practices, such as proper comments etc.

The gap was intentional so that it seemed like they were hovering but I've reduced it and I've added proper comments.

**Pull request merged**
