### PR TITLE
Hacktoberfest 2022 - Adding Glow Animation example

### PR DESCRIPTION
**Pull request by HarineMurugan**
Added example for glow animation.
Screenshot during animation - 
image

### CODE REVIEW

**Comment by UsmanAhmadSaeed** [comment]
@HarineMurugan I've reviewed your code. Please take a look at contribution guidelines of project, and update your PR accordingly. For example, add comments in your code.
Further, your animation looks more like a load screen animation. Kindly classify it under that.

**Comment by HarineMurugan** [comment]
@UsmanAhmadSaeed Added comments and moved to load animation. Would you please check and let me know if it is good?

**Comment by UsmanAhmadSaeed** [comment]
@HarineMurugan Comments could be better and more descriptive.

**Comment by HarineMurugan** [comment]
Added more comments @UsmanAhmadSaeed

**Pull request merged**
